apiVersion: actions.github.com/v1alpha1
kind: AutoScaleRunner
metadata:
  name: auto-scale-runners
spec:
  minReplicas: 1
  maxReplicas: 5
  configURL: https://github.com/TingluoHuang/example-services
  githubTokenSecretKeyRef:
    name: githubtoken
    key: GITHUB_PAT
  template:
    spec:
      setupDockerInDocker: true
