name: Docker Image CI

on:
  push:
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd src
        echo "${{secrets.docker_hub_token}}" | docker login --username huangtingluo --password-stdin 
        docker build . --file Dockerfile --tag huangtingluo/kube-runner:v0
        docker push huangtingluo/kube-runner:v0